// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYv0F_nNlVGCXL9xiOeoFvgIZESAwh2bc',
    appId: '1:254808712492:web:d2b169df172bd52315b889',
    messagingSenderId: '254808712492',
    projectId: 'quizapp-3107f',
    authDomain: 'quizapp-3107f.firebaseapp.com',
    storageBucket: 'quizapp-3107f.appspot.com',
    measurementId: 'G-CDND40VN22',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCC6tWPEF50Q-79-CGz0P2D_4CUYZguL6g',
    appId: '1:254808712492:android:3caa0528f908e41e15b889',
    messagingSenderId: '254808712492',
    projectId: 'quizapp-3107f',
    storageBucket: 'quizapp-3107f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMy8bVWurTLoTqgmWiEm9vKlGouvtG1JU',
    appId: '1:254808712492:ios:0a6a5e66aea3d01d15b889',
    messagingSenderId: '254808712492',
    projectId: 'quizapp-3107f',
    storageBucket: 'quizapp-3107f.appspot.com',
    iosClientId: '254808712492-av25gf5unfqafadbl8j1p1ktep13ushi.apps.googleusercontent.com',
    iosBundleId: 'com.codefox.quizzle',
  );
}
